# Generated by Django 3.1.6 on 2021-02-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_testtable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testtable',
            new_name='Test_Table',
        ),
    ]
